
var AIQ=AIQ||{};(function(){"use strict";AIQ.Core=AIQ.Core||{};AIQ._applicationId=-1;function checkComplete(){if(document.readyState!=="complete"){return setTimeout(checkComplete,0);}
var e=document.createEvent("Events");e.initEvent("aiq-ready",false,false);document.dispatchEvent(e);}
checkComplete();}());(function(){"use strict";if(!AIQ.Core.App){AIQ.Core.App={};AIQ.Core.App.setTitle=function(title){document.title=title;};AIQ.Core.App.close=function(){};}}());(function(){"use strict";if(!AIQ.Core.Context){AIQ.Core.Context={};AIQ.Core.Context.getGlobal=function(providerName,settings){if(!settings){return;}
var callbacks={success:settings.success||function(){},failure:settings.failure||function(){}};var getContextDoc=function(contextType,callbacks){AIQ.Core.DataSync.getDocuments(contextType,{success:function(docs){if((docs.length>0)&&(docs[0].hasOwnProperty("providerName"))){callbacks.success(docs[0][providerName]);}else{callbacks.failure();}}});};getContextDoc("_clientcontext",{success:callbacks.success,failure:function(){getContextDoc("_backendcontext",callbacks);}});};AIQ.Core.Context.getLocal=function(key,settings){if(!settings){return;}
var callbacks={success:settings.success||function(){},failure:settings.failure||function(){}};AIQ.Core.DataSync.getDocuments("_clientcontext",{success:function(docs){if(docs.length>0){var doc=docs[0];if(doc.hasOwnProperty("com.appearnetworks.aiq.apps")){var appContext=doc["com.appearnetworks.aiq.apps"];if(appContext.hasOwnProperty(key)){callbacks.success(appContext[key]);return;}}}
callbacks.failure();}});};AIQ.Core.Context.setLocal=function(key,value,settings){settings=settings||{};var callbacks={success:settings.success||function(){},failure:settings.failure||function(){}};AIQ.Core.DataSync.getDocuments("_clientcontext",{success:function(docs){var doc;if(docs.length>0){doc=docs[0];doc["com.appearnetworks.aiq.apps"]=doc["com.appearnetworks.aiq.apps"]||{};doc["com.appearnetworks.aiq.apps"][key]=value;AIQ.Core.DataSync.updateDocument(doc._id,doc,callbacks);}else{doc={};doc["com.appearnetworks.aiq.apps"]={};doc["com.appearnetworks.aiq.apps"][key]=value;AIQ.Core.DataSync.createDocument("_clientcontext",doc,callbacks);}}});};}}());(function(){"use strict";if(!AIQ.Core.DataSync){AIQ.Core.DataSync={};AIQ.Core.DataSync.registeredCallbacks=[];AIQ.Core.DataSync.idCount=0;AIQ.Core.DataSync.getDocument=function(id,settings){if(id===AIQ._applicationId){return settings.success({name:"Mock App name"});}
var document;var docs=localStorage["AIQ.Documents"]?JSON.parse(localStorage["AIQ.Documents"]):[];var i;for(i=0;i<docs.length;i++){if(docs[i]._id===id){document=docs[i];}}
setTimeout(function(){if(document){settings.success(document);}else{settings.failure();}},500);};AIQ.Core.DataSync.getAttachment=function(id,name,settings){var result;var store=localStorage["AIQ.Attachments"]?JSON.parse(localStorage["AIQ.Attachments"]):{};var attachments=store[id];if(attachments!==undefined){var attachment=attachments[name];if(attachment!==undefined){result={name:name,contentType:attachment.contentType,resourceId:attachment.resourceId,state:"available"};}}
setTimeout(function(){if(result){settings.success(result);}else if(settings.failure){settings.failure();}},500);};AIQ.Core.DataSync.getDocuments=function(type,settings){var docs=localStorage["AIQ.Documents"]?JSON.parse(localStorage["AIQ.Documents"]):[];var typedDocs=[];var i;for(i=0;i<docs.length;i++){if(docs[i]._type===type){typedDocs.push(docs[i]);}}
setTimeout(function(){settings.success(typedDocs);},500);};AIQ.Core.DataSync.getAttachments=function(id,settings){var result=[];var store=localStorage["AIQ.Attachments"]?JSON.parse(localStorage["AIQ.Attachments"]):{};var attachments=store[id];if(attachments!==undefined){var name;for(name in attachments){if(attachments.hasOwnProperty(name)){result.push({name:name,contentType:attachments[name].contentType,resourceId:attachments[name].resourceId,state:"available"});}}}
setTimeout(function(){settings.success(result);},500);};AIQ.Core.DataSync.createDocument=function(type,object,settings){var docs=localStorage["AIQ.Documents"]?JSON.parse(localStorage["AIQ.Documents"]):[];object._id=+new Date()+"-"+(++AIQ.Core.DataSync.idCount);object._type=type;object._rev=0;docs.push(object);localStorage["AIQ.Documents"]=JSON.stringify(docs);AIQ.Core.DataSync.triggerDocumentEvent("document-created",type,object._id);if(settings!==undefined){return settings.success(object);}};AIQ.Core.DataSync.updateDocument=function(id,object,settings){var docs=localStorage["AIQ.Documents"]?JSON.parse(localStorage["AIQ.Documents"]):[];var i;for(i=0;i<docs.length;i++){if(docs[i]._id===id){object._id=docs[i]._id;object._rev=docs[i]._rev;object._type=docs[i]._type;object._launchable=docs[i]._launchable;docs[i]=object;localStorage["AIQ.Documents"]=JSON.stringify(docs);AIQ.Core.DataSync.triggerDocumentEvent("document-updated",object._type,id);return settings.success?settings.success(docs[i]):undefined;}}
if(settings.failure){settings.failure();}};AIQ.Core.DataSync.deleteDocument=function(id,settings){var docs=localStorage["AIQ.Documents"]?JSON.parse(localStorage["AIQ.Documents"]):[];var i;for(i=0;i<docs.length;i++){if(docs[i]._id===id){var type=docs[i]._type;docs.splice(i,1);localStorage["AIQ.Documents"]=JSON.stringify(docs);AIQ.Core.DataSync.triggerDocumentEvent("document-deleted",type,id);return settings.success();}}
if(settings.failure){settings.failure();}};AIQ.Core.DataSync.deleteAttachment=function(id,name,settings){var docs=localStorage["AIQ.Documents"]?JSON.parse(localStorage["AIQ.Documents"]):{};var i;for(i=0;i<docs.length;i++){if(docs[i]._id===id){if(docs[i]._attachments[name]!==undefined){delete docs[i]._attachments[name];localStorage["AIQ.Documents"]=JSON.stringify(docs);return settings.success();}}}
if(settings.failure){settings.failure();}};AIQ.Core.DataSync.synchronize=function(){setTimeout(function(){AIQ.Core.DataSync.triggerDocumentEvent("synchronization-complete");},1500);};var _events={};var _documentEvents={};var _attachmentEvents={};var fireCallbacks=function(event,args){_events[event].forEach(function(c){c();});};var fireDocumentCallbacks=function(event,args){var types=_documentEvents[event];if(types){var local=(args._caller===AIQ._applicationId);if(types.hasOwnProperty("__all__")){types.__all__.forEach(function(c){c(args._id,local);});}
if(types.hasOwnProperty(args._type)){types[args._type].forEach(function(c){c(args._id,local);});}}};var fireAttachmentCallbacks=function(event,args){var ids=_attachmentEvents[event];if(ids){if(ids.hasOwnProperty("__all__")){ids.__all__.forEach(function(c){c(args._id,args._name);});}
if(ids.hasOwnProperty(args._name)){ids[args._name].forEach(function(c){c(args._id,args._name);});}}
if(ids.hasOwnProperty(args._id)){var names=ids[args._id];if(names.hasOwnProperty("__all__")){names.__all__.forEach(function(c){c(args._id,args._name);});}
if(names.hasOwnProperty(args._name)){names[args._name].forEach(function(c){c(args._id,args._name);});}}};AIQ.Core.DataSync.triggerDocumentEvent=function(event,type,documentId){fireDocumentCallbacks(event,{_type:type,_id:documentId,_caller:AIQ._applicationId});};AIQ.Core.DataSync.bindDocumentEvent=function(event,type,callback){var types=_documentEvents[event];if(!types){types={};_documentEvents[event]=types;}
if(!type){type="__all__";}
var callbacks=types[type];if(!callbacks){callbacks=[];types[type]=callbacks;}
callbacks.push(callback);};AIQ.Core.DataSync.bindAttachmentEvent=function(event,id,name,callback){var ids=_attachmentEvents[event];if(!ids){ids={};_attachmentEvents[event]=ids;}
if(!id){id="__all__";}
var names=ids[id];if(!names){names={};ids[id]=names;}
if(!name){name="__all__";}
var callbacks=names[name];if(!callbacks){callbacks=[];names[name]=callbacks;}
callbacks.push(callback);};AIQ.Core.DataSync.bindEvent=function(event,callback){var callbacks=_events[event];if(!callbacks){callbacks=[];_events[event]=callbacks;}
callbacks.push(callback);};AIQ.Core.DataSync.unbind=function(callback){var event;var callbacks;var index;for(event in _events){if(_events.hasOwnProperty(event)){callbacks=_events[event];while((index=callbacks.indexOf(callback))>-1){callbacks.splice(index,1);}
_events[event]=callbacks;}}
for(event in _documentEvents){if(_documentEvents.hasOwnProperty(event)){var type;for(type in _documentEvents[event]){if(_documentEvents[event].hasOwnProperty(type)){callbacks=_documentEvents[event][type];while((index=callbacks.indexOf(callback))>-1){callbacks.splice(index,1);}
_documentEvents[event][type]=callbacks;}}}}
for(event in _attachmentEvents){if(_attachmentEvents.hasOwnProperty(event)){var id;for(id in _attachmentEvents[event]){if(_attachmentEvents[event].hasOwnProperty(id)){var name;for(name in _attachmentEvents[event][id]){if(_attachmentEvents[event][id].hasOwnProperty(name)){callbacks=_attachmentEvents[event][id][name];while((index=callbacks.indexOf(callback))>-1){callbacks.splice(index,1);}
_attachmentEvents[event][id][name]=callbacks;}}}}}}};AIQ.Core.DataSync.getConnectionStatus=function(callback){callback(true);};}}());(function(){"use strict";if(!AIQ.Core.Direct){AIQ.Core.Direct={};AIQ.Core.Direct.call=function(args,settings){settings=settings||{};if((args)&&(args.endpoint)){args.method=args.method||"get";$.ajax({url:args.endpoint+'.'+args.method.toLowerCase(),dataType:"json",async:true,cache:false}).done(function(data,textStatus,jqXHR){if(data.errorCode){if(settings.failure){settings.failure(data.errorCode);}}else{var result={};if(args.params){var i;for(i=0;i<data.length;i++){var doc=data[i];var matches=true;var param;for(param in doc){if(doc.hasOwnProperty(param)){if(param!=="data"){var value=String(args.params[param]);var match=value.match(String(doc[param]));if((!match)||(match.length!==1)||(match[0]!==value)){matches=false;break;}}}}
if(matches){result=doc.data;break;}}}else{result=data;}
if(result.errorCode){if(settings.failure){settings.failure(result.errorCode);}}else if(settings.success){settings.success(result);}}}).fail(function(jqXHR,textStatus,errorThrown){if(jqXHR.status===200){if(settings.error){settings.error({message:errorThrown});}}else if(settings.failure){settings.failure(jqXHR.status);}});}else if(settings.failure){settings.failure(-1);}};}}());(function(){"use strict";if(!AIQ.Core.Display){AIQ.Core.Display={};AIQ.Core.Display.setOrientation=function(orientation){};}}());(function(){"use strict";if(!AIQ.Core.Imaging){AIQ.Core.Imaging={};AIQ.Core.Imaging.idCount=0;AIQ.Core.Imaging.getImage=function(id,settings){AIQ.Core.DataSync.getDocument(id,{success:function(doc){var store=localStorage["AIQ.Attachments"]?JSON.parse(localStorage["AIQ.Attachments"]):{};var attachments=store[id];if(attachments===undefined){attachments={};}
var count=0;var name;for(name in attachments){if(attachments.hasOwnProperty(name)){count++;}}
name="content_"+count+".png";var resourceId="css/assets/picture"+(count%2+1)+".png";var attachment={contentType:"image/png",resourceId:resourceId};attachments[name]=attachment;store[id]=attachments;localStorage["AIQ.Attachments"]=JSON.stringify(store);settings.success({name:name,contentType:"image/png",state:"available",resourceId:resourceId});},failure:function(){if(settings.failure){settings.failure({cancel:false});}},error:function(arg){if(settings.error){settings.error(arg);}}});};}}());(function(){"use strict";if(!AIQ.External){AIQ.External={};}
if(!AIQ.External.Maps){AIQ.External.Maps={};AIQ.External.Maps.open=function(settings){};}}());(function(){"use strict";if(!AIQ.Core.Messaging){AIQ.Core.Messaging={};AIQ.Core.Messaging.getMessages=function(type,settings){var messages=localStorage['AIQ.Messages']?JSON.parse(localStorage['AIQ.Messages']):[];var typedMessages=[];var i;for(i=0;i<messages.length;i++){if(messages[i].type===type){typedMessages.push(messages[i]);}}
setTimeout(function(){settings.success(typedMessages);},500);};AIQ.Core.Messaging.markMessageAsRead=function(id,settings){var messages=localStorage['AIQ.Messages']?JSON.parse(localStorage['AIQ.Messages']):[];var i;for(i=0;i<messages.length;i++){if(messages[i]._id===id){messages[i].read=true;localStorage['AIQ.Messages']=JSON.stringify(messages);return settings.success(messages[i]);}}
if(settings.failure){settings.failure();}};var _messageEvents={};AIQ.Core.Messaging.bindMessageEvent=function(event,type,callback){var messageTypes=_messageEvents[event];if(!messageTypes){_messageEvents[event]=messageTypes={};}
if(!type){type="__all__";}
var callbacks=messageTypes[type];if(!callbacks){messageTypes[type]=callbacks=[];}
callbacks.push(callback);};AIQ.Core.Messaging.unbind=function(callback){var event;for(event in _messageEvents){if(_messageEvents.hasOwnProperty(event)){var type;for(type in _messageEvents[event]){if(_messageEvents[event].hasOwnProperty(type)){var callbacks=_messageEvents[event][type];var index;while((index=callbacks.indexOf(callback))>-1){callbacks.splice(index,1);}
_messageEvents[event][type]=callbacks;}}}}};}}());